import type { Metadata } from "next";
import '@/Styles/style.scss'
import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "Simple Profile",
  description: "Generated by create next app",  
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: '500'
});

export default async function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang='pt-BR'>
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  );
}