import type { Metadata } from "next";
import '@/Styles/style.scss'
import { Inter } from "next/font/google";
// import { i18n, type Locale } from "../../i18n";

// export async function generateStaticParams() {
//   return i18n.locales.map((locale) => ({ lang: locale }));
// }



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default async function LocaleLayout({
  children,
  // params
}: {
  children: React.ReactNode;
  // params: { locale: Locale };
}) {

  return (
    <html lang='pt-BR'>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}