import type { Metadata } from "next";
import '@/Styles/style.scss'
// import { NextIntlClientProvider } from 'next-intl';
// import { getMessages } from 'next-intl/server';
import { Inter } from "next/font/google";
import { i18n, type Locale } from "../../../i18n-config";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { locale: Locale };
}) {
  // const messages = await getMessages();
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        {/* <NextIntlClientProvider messages={messages}> */}
        {children}
        {/* </NextIntlClientProvider> */}
      </body>
    </html>
  );
}